server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdqn?serverTimezone=UTC
    username: root
    password: 1234
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.bdqn.provider.entity
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://localhost:10086/eureka